# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import storage_pb2 as storage__pb2


class StorageServicerStub(object):
    """Interface exported by the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Alive = channel.unary_unary(
                '/routeguide.StorageServicer/Alive',
                request_serializer=storage__pb2.FeatureS.SerializeToString,
                response_deserializer=storage__pb2.FeatureS.FromString,
                )
        self.Update_list = channel.unary_unary(
                '/routeguide.StorageServicer/Update_list',
                request_serializer=storage__pb2.Address_listS.SerializeToString,
                response_deserializer=storage__pb2.FeatureS.FromString,
                )
        self.Get_stor_nodes = channel.unary_unary(
                '/routeguide.StorageServicer/Get_stor_nodes',
                request_serializer=storage__pb2.FeatureS.SerializeToString,
                response_deserializer=storage__pb2.Address_listS.FromString,
                )
        self.Ask_for_file = channel.unary_stream(
                '/routeguide.StorageServicer/Ask_for_file',
                request_serializer=storage__pb2.FeatureS.SerializeToString,
                response_deserializer=storage__pb2.DataS.FromString,
                )
        self.Ask_if_name_belongs = channel.unary_unary(
                '/routeguide.StorageServicer/Ask_if_name_belongs',
                request_serializer=storage__pb2.FeatureS.SerializeToString,
                response_deserializer=storage__pb2.Bool.FromString,
                )
        self.Register_user = channel.unary_unary(
                '/routeguide.StorageServicer/Register_user',
                request_serializer=storage__pb2.User_data.SerializeToString,
                response_deserializer=storage__pb2.Log_token.FromString,
                )
        self.Login_user = channel.unary_unary(
                '/routeguide.StorageServicer/Login_user',
                request_serializer=storage__pb2.User_data.SerializeToString,
                response_deserializer=storage__pb2.Log_token.FromString,
                )
        self.Random_n = channel.unary_stream(
                '/routeguide.StorageServicer/Random_n',
                request_serializer=storage__pb2.IdvalueS.SerializeToString,
                response_deserializer=storage__pb2.DataS.FromString,
                )
        self.Get_following = channel.unary_unary(
                '/routeguide.StorageServicer/Get_following',
                request_serializer=storage__pb2.IdvalueS.SerializeToString,
                response_deserializer=storage__pb2.Id_list.FromString,
                )
        self.Followed_tweets = channel.unary_stream(
                '/routeguide.StorageServicer/Followed_tweets',
                request_serializer=storage__pb2.Id_list.SerializeToString,
                response_deserializer=storage__pb2.DataS.FromString,
                )
        self.Tweet = channel.unary_unary(
                '/routeguide.StorageServicer/Tweet',
                request_serializer=storage__pb2.AddressS.SerializeToString,
                response_deserializer=storage__pb2.FeatureS.FromString,
                )
        self.Retweet = channel.unary_unary(
                '/routeguide.StorageServicer/Retweet',
                request_serializer=storage__pb2.Comment_info.SerializeToString,
                response_deserializer=storage__pb2.FeatureS.FromString,
                )
        self.Follow = channel.unary_unary(
                '/routeguide.StorageServicer/Follow',
                request_serializer=storage__pb2.Follow_info.SerializeToString,
                response_deserializer=storage__pb2.FeatureS.FromString,
                )
        self.Comment = channel.unary_unary(
                '/routeguide.StorageServicer/Comment',
                request_serializer=storage__pb2.Comment_info.SerializeToString,
                response_deserializer=storage__pb2.FeatureS.FromString,
                )


class StorageServicerServicer(object):
    """Interface exported by the server.
    """

    def Alive(self, request, context):
        """Basic message to recognize if there is a steady connection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update_list(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get_stor_nodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ask_for_file(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ask_if_name_belongs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register_user(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login_user(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Random_n(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get_following(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Followed_tweets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tweet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retweet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Follow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Comment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageServicerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Alive': grpc.unary_unary_rpc_method_handler(
                    servicer.Alive,
                    request_deserializer=storage__pb2.FeatureS.FromString,
                    response_serializer=storage__pb2.FeatureS.SerializeToString,
            ),
            'Update_list': grpc.unary_unary_rpc_method_handler(
                    servicer.Update_list,
                    request_deserializer=storage__pb2.Address_listS.FromString,
                    response_serializer=storage__pb2.FeatureS.SerializeToString,
            ),
            'Get_stor_nodes': grpc.unary_unary_rpc_method_handler(
                    servicer.Get_stor_nodes,
                    request_deserializer=storage__pb2.FeatureS.FromString,
                    response_serializer=storage__pb2.Address_listS.SerializeToString,
            ),
            'Ask_for_file': grpc.unary_stream_rpc_method_handler(
                    servicer.Ask_for_file,
                    request_deserializer=storage__pb2.FeatureS.FromString,
                    response_serializer=storage__pb2.DataS.SerializeToString,
            ),
            'Ask_if_name_belongs': grpc.unary_unary_rpc_method_handler(
                    servicer.Ask_if_name_belongs,
                    request_deserializer=storage__pb2.FeatureS.FromString,
                    response_serializer=storage__pb2.Bool.SerializeToString,
            ),
            'Register_user': grpc.unary_unary_rpc_method_handler(
                    servicer.Register_user,
                    request_deserializer=storage__pb2.User_data.FromString,
                    response_serializer=storage__pb2.Log_token.SerializeToString,
            ),
            'Login_user': grpc.unary_unary_rpc_method_handler(
                    servicer.Login_user,
                    request_deserializer=storage__pb2.User_data.FromString,
                    response_serializer=storage__pb2.Log_token.SerializeToString,
            ),
            'Random_n': grpc.unary_stream_rpc_method_handler(
                    servicer.Random_n,
                    request_deserializer=storage__pb2.IdvalueS.FromString,
                    response_serializer=storage__pb2.DataS.SerializeToString,
            ),
            'Get_following': grpc.unary_unary_rpc_method_handler(
                    servicer.Get_following,
                    request_deserializer=storage__pb2.IdvalueS.FromString,
                    response_serializer=storage__pb2.Id_list.SerializeToString,
            ),
            'Followed_tweets': grpc.unary_stream_rpc_method_handler(
                    servicer.Followed_tweets,
                    request_deserializer=storage__pb2.Id_list.FromString,
                    response_serializer=storage__pb2.DataS.SerializeToString,
            ),
            'Tweet': grpc.unary_unary_rpc_method_handler(
                    servicer.Tweet,
                    request_deserializer=storage__pb2.AddressS.FromString,
                    response_serializer=storage__pb2.FeatureS.SerializeToString,
            ),
            'Retweet': grpc.unary_unary_rpc_method_handler(
                    servicer.Retweet,
                    request_deserializer=storage__pb2.Comment_info.FromString,
                    response_serializer=storage__pb2.FeatureS.SerializeToString,
            ),
            'Follow': grpc.unary_unary_rpc_method_handler(
                    servicer.Follow,
                    request_deserializer=storage__pb2.Follow_info.FromString,
                    response_serializer=storage__pb2.FeatureS.SerializeToString,
            ),
            'Comment': grpc.unary_unary_rpc_method_handler(
                    servicer.Comment,
                    request_deserializer=storage__pb2.Comment_info.FromString,
                    response_serializer=storage__pb2.FeatureS.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'routeguide.StorageServicer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StorageServicer(object):
    """Interface exported by the server.
    """

    @staticmethod
    def Alive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.StorageServicer/Alive',
            storage__pb2.FeatureS.SerializeToString,
            storage__pb2.FeatureS.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update_list(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.StorageServicer/Update_list',
            storage__pb2.Address_listS.SerializeToString,
            storage__pb2.FeatureS.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get_stor_nodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.StorageServicer/Get_stor_nodes',
            storage__pb2.FeatureS.SerializeToString,
            storage__pb2.Address_listS.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Ask_for_file(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/routeguide.StorageServicer/Ask_for_file',
            storage__pb2.FeatureS.SerializeToString,
            storage__pb2.DataS.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Ask_if_name_belongs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.StorageServicer/Ask_if_name_belongs',
            storage__pb2.FeatureS.SerializeToString,
            storage__pb2.Bool.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Register_user(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.StorageServicer/Register_user',
            storage__pb2.User_data.SerializeToString,
            storage__pb2.Log_token.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Login_user(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.StorageServicer/Login_user',
            storage__pb2.User_data.SerializeToString,
            storage__pb2.Log_token.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Random_n(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/routeguide.StorageServicer/Random_n',
            storage__pb2.IdvalueS.SerializeToString,
            storage__pb2.DataS.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get_following(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.StorageServicer/Get_following',
            storage__pb2.IdvalueS.SerializeToString,
            storage__pb2.Id_list.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Followed_tweets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/routeguide.StorageServicer/Followed_tweets',
            storage__pb2.Id_list.SerializeToString,
            storage__pb2.DataS.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Tweet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.StorageServicer/Tweet',
            storage__pb2.AddressS.SerializeToString,
            storage__pb2.FeatureS.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retweet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.StorageServicer/Retweet',
            storage__pb2.Comment_info.SerializeToString,
            storage__pb2.FeatureS.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Follow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.StorageServicer/Follow',
            storage__pb2.Follow_info.SerializeToString,
            storage__pb2.FeatureS.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Comment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.StorageServicer/Comment',
            storage__pb2.Comment_info.SerializeToString,
            storage__pb2.FeatureS.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
